service: cve-db
frameworkVersion: '3'

custom:
  cveFilehashDb: cve-db-filehashes
  # collectorBucket: elastifeed-collector-data-${self:provider.stage}

  # -${self:provider.stage}

provider:
  name: aws
  runtime: python3.9
  environment:
      ATHENA_OUTPUT_BUCKET: !Ref AthenaResultsBucket
      CVE_FILE_HASH_DB: !Ref CVEFileHashDb
  iamRoleStatements:
    - Effect: Allow
      Action:
        - 's3:PutObject'
        - 's3:GetObject'
        - 's3:GetBucketLocation'
        - 's3:ListBucket'
        - 's3:*'
      Resource: 
        - Fn::Join:
          - ""
          - - "arn:aws:s3:::"
            - Ref: AthenaResultsBucket
        - Fn::Join:
          - ""
          - - "arn:aws:s3:::"
            - Ref: AthenaResultsBucket
            - "/*"
    - Effect: Allow
      Action:
        - 'athena:StartQueryExecution'
        - 'athena:GetQueryExecution'
        - 'athena:GetQueryResults'
      Resource: '*'
    - Effect: Allow
      Action:
        - 's3:GetObject'
        - 's3:GetBucketLocation'
        - 's3:ListBucket'
        - 's3:*'
      Resource: 
        - arn:aws:s3:::elasticninja-cvedb
        - arn:aws:s3:::elasticninja-cvedb/*
    - Effect: Allow
      Action:
        - 'glue:*'
      Resource: '*'
  ecr:
    images:
      cvedb:
        path: .

functions:
  # cve_by_id:
  #   handler: handler.cve_by_id
  #   events:
  #     - http:
  #         path: /cve/id/{cveid}
  #         method: get
  update_cve_db:
    timeout: 900
    memorySize: 4096
    ephemeralStorageSize: 10240
    image:
      name: cvedb
    # handler: handler.hello
    events:
      - schedule: cron(0 2 * * ? *)

resources:
  Resources:
    AthenaResultsBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: elasticninja-cvedb-results2
    CVEFileHashDb:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: ${self:custom.cveFilehashDb}
        AttributeDefinitions:
          - AttributeName: 'cveid'
            AttributeType: 'S'
          # - AttributeName: 'filehash'
          #   AttributeType: 'S'
        KeySchema:
          - AttributeName: 'cveid'
            KeyType: 'HASH'
        BillingMode: PAY_PER_REQUEST
